-- MySQL Script generated by MySQL Workbench
-- Sun Oct 13 16:23:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `edad` SMALLINT(2) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profesor` (
  `idprofesor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `materia` VARCHAR(45) NULL,
  PRIMARY KEY (`idprofesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesion` (
  `idsesion` INT NOT NULL,
  `hora` TIME NULL,
  `fecha` DATE NULL,
  `duracion` TIME NULL,
  `precio` FLOAT NULL,
  `lugar` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `materia` VARCHAR(45) NULL,
  `idusuario` INT NOT NULL,
  `idprofesor` INT NOT NULL,
  PRIMARY KEY (`idsesion`, `idusuario`, `idprofesor`),
  INDEX `fk_sesion_usuario_idx` (`idusuario` ASC),
  INDEX `fk_sesion_profesor1_idx` (`idprofesor` ASC),
  CONSTRAINT `fk_sesion_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesion_profesor1`
    FOREIGN KEY (`idprofesor`)
    REFERENCES `profesor` (`idprofesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factura` (
  `idfactura` INT NOT NULL,
  `valor` FLOAT ZEROFILL NULL,
  `estado` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `idsesion` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idfactura`, `idsesion`, `idusuario`),
  INDEX `fk_factura_sesion1_idx` (`idsesion` ASC, `idusuario` ASC),
  CONSTRAINT `fk_factura_sesion1`
    FOREIGN KEY (`idsesion` , `idusuario`)
    REFERENCES `sesion` (`idsesion` , `idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporte` (
  `sesion_idsesion` INT NOT NULL,
  `sesion_idusuario` INT NOT NULL,
  `sesion_idprofesor` INT NOT NULL,
  `nota` INT NULL,
  `observaciones` VARCHAR(255) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`sesion_idsesion`, `sesion_idusuario`, `sesion_idprofesor`),
  CONSTRAINT `fk_table1_sesion1`
    FOREIGN KEY (`sesion_idsesion` , `sesion_idusuario` , `sesion_idprofesor`)
    REFERENCES `sesion` (`idsesion` , `idusuario` , `idprofesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
